### ISSUE TITLE
Change basemap to Mapbox

### ISSUE THREAD

**Issue by rhb1** [azgs/hazards-viewer#22]
Base map - see http://cropmap.arizona.experience.org/

**Comment by rhb1** [comment]
updated with commit b072d3d9522063e2bbf04c0255f17ec71ceb09ff

**Comment by asonnenschein** [comment]
@rhb1 You might want to have a look at Bing's TOS with this change.  The geolocation functionality in this application runs off of Bing's engine and if I recall correctly, Bing's geolocation service is only allowed to be used on top of Bing base maps.  Also, Bing maps are based off of proprietary data sources and Mapbox maps are based off Open Street Map; matching up addresses across the two different sources might throw things off.

BTW, my comment here is based off of project planning from 2+ years ago.  Things might have changed with Bing in the meantime, but always best to play it safe with TOS.
