### ISSUE TITLE
Earthquakes Layers Not Filtering Correctly

### ISSUE THREAD

**Issue by jessica-azgs** [azgs/hazards-viewer#28]
For example, turn on only the earthquakes with magnitude 2-3. Some of the data points actually say magnitude of 1.9 or magnitude above 3. (Can see several near Yuma and just across the border if you zoom in there.) This same filtering error happens with different magnitude filtering layers as well.

Could you look at this @rhb1?

**Comment by rhb1** [comment]
fixed with - 14747baf1de8635c6867ecb246d7ca881d687e30 for now

**Comment by rhb1** [comment]
added magnitude 1 -2 class 060a24bf201e14dbe7a06b88c368774d88c453fa
